version: "3"

networks:
    laravel:

services:
    nginx:
        image: nginx:stable-alpine
        ports:
            - "8080:8080"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - composer
            - php
        restart: always
        networks:
            - laravel

    php:
        build:
            context: .
            dockerfile: Dockerfile.php
        ports:
            - "8081:8081"
        restart: always
        depends_on:
            - composer
        networks:
            - laravel

    composer:
        build:
            context: ./
            dockerfile: Dockerfile.composer
        volumes:
            - ./:/app
        working_dir: /app
        restart: always
        networks:
            - laravel
