version: "3"

networks:
    laravel:

services:
    nginx:
        build:
            context: ./
            dockerfile: Dockerfile.nginx
        container_name: laravel-nginx
        ports:
            - "8080:8080"
        volumes:
            - ./:/app
        depends_on:
            - composer
            - php
        restart: unless-stopped
        networks:
            - laravel

    php:
        build:
            context: ./
            dockerfile: Dockerfile.php
        container_name: laravel-php
        ports:
            - "8081:8081"
        links:
            - composer
        restart: unless-stopped
        working_dir: /app
        depends_on:
            - composer
        networks:
            - laravel

    composer:
        build:
            context: ./
            dockerfile: Dockerfile.composer
        container_name: laravel-composer
        volumes:
            - ./:/app
        working_dir: /app
        restart: unless-stopped
        networks:
            - laravel
