version: "3"

networks:
    laravel:

services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: laravel/laravel-app
        container_name: laravel-app
        volumes:
            - ./:/app
        ports:
            - 8081:8081
        networks:
            - laravel

    nginx:
        build:
            context: ./
            dockerfile: Dockerfile.nginx
        image: laravel/laravel-nginx
        container_name: laravel-nginx
        volumes:
            - ./:/app
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8080:8080
        working_dir: /app
        networks:
            - laravel
