version: "3"

networks:
    laravel:

services:
    nginx:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: laravel-nginx
        ports:
            - 8080:8080
        environment:
            NODE_ENV: development
        depends_on:
            - composer
            - php
        networks:
            - laravel
