version: "3"

networks:
    laravel:

services:
    composer:
        build:
            context: ./docker
            dockerfile: composer.dockerfile
        volumes:
            - .:/var/www/html
        networks:
            - laravel

    php:
        build:
            context: ./docker
            dockerfile: php.dockerfile
        volumes:
            - .:/var/www/html
        networks:
            - laravel

    nginx:
        build:
            context: ./docker
            dockerfile: nginx.dockerfile
        container_name: laravel-nginx
        ports:
            - 8080:8080
        environment:
            NODE_ENV: development
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel
