version: "3"

networks:
    laravel:

services:
    nginx:
        build:
            context: ./docker
            dockerFile: nginx.dockerfile
            container_name: laravel-nginx
            ports:
                - 8080:8080
            environment:
                NODE_ENV: development
            depends_on:
                - composer
                - php
        networks:
            - laravel

    composer:
        build:
            context: ./docker
            dockerFile: composer.dockerfile
            container_name: laravel-composer
        networks:
            - laravel

    php:
        build:
            context: ./docker
            dockerFile: php.dockerfile
            container_name: laravel-php
            depends_on:
                - composer
        networks:
            - laravel
