version: "3"

networks:
    laravel:

services:
    nginx:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: laravel-nginx
        ports:
            - 8080:8080
        networks:
            - laravel
