version: "3"

services:
    nginx:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: laravel-nginx
        ports:
            - 8080:8080
        environment:
            NODE_ENV: development
