version: "3"

networks:
    laravel:

services:
    nginx:
        build:
            context: ./docker
            dockerfile: nginx.dockerfile
        container_name: laravel-nginx
        ports:
            - 8080:8080
        environment:
            NODE_ENV: development
        depends_on:
            - composer
            - php
        networks:
            - laravel

    composer:
        build:
            context: ./docker
            dockerfile: composer.dockerfile
        networks:
            - laravel

    php:
        build:
            context: ./docker
            dockerfile: php.dockerfile
        depends_on:
            - composer
        networks:
            - laravel
